/**
 * Forth Built-in Function & Keyword Documentation Registry
 */
import { Opcode, WordMetadata } from './types.ts';

export const FORTH_DOCS: WordMetadata[] = [
  // --- Stack Manipulation ---
  {
    name: 'DUP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- x x )',
    category: 'Stack',
    summary: 'Duplicate the top stack item',
    description: 'Pushes a copy of the top stack item (TOS) onto the stack.',
    example: '5 DUP * .   \\ computes 5 * 5 = 25',
    opcode: Opcode.DUP,
  },
  {
    name: '?DUP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- 0 | x x )',
    category: 'Stack',
    summary: 'Duplicate TOS if it is non-zero',
    description: 'Duplicates the top stack item only if it is non-zero; otherwise leaves the 0 on top.',
    example: '10 ?DUP . .  \\ prints 10 10\n0 ?DUP .    \\ prints 0',
    opcode: Opcode.QDUP,
  },
  {
    name: 'DROP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- )',
    category: 'Stack',
    summary: 'Discard the top stack item',
    description: 'Removes the top item from the data stack.',
    example: '10 20 DROP .  \\ prints 10',
    opcode: Opcode.DROP,
  },
  {
    name: 'SWAP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x2 x1 )',
    category: 'Stack',
    summary: 'Exchange top two stack items',
    description: 'Swaps the positions of the top two stack items.',
    example: '10 20 SWAP . .  \\ prints 10 20',
    opcode: Opcode.SWAP,
  },
  {
    name: 'OVER',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x1 x2 x1 )',
    category: 'Stack',
    summary: 'Copy second item to top',
    description: 'Copies the second item on the stack (NOS - Next on Stack) to the top of the stack.',
    example: '10 20 OVER . . .  \\ prints 10 20 10',
    opcode: Opcode.OVER,
  },
  {
    name: 'ROT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 x3 -- x2 x3 x1 )',
    category: 'Stack',
    summary: 'Rotate top three items',
    description: 'Rotates the third item on the stack to the top, shifting the top two down.',
    example: '1 2 3 ROT . . .  \\ prints 1 3 2',
    opcode: Opcode.ROT,
  },
  {
    name: '-ROT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 x3 -- x3 x1 x2 )',
    category: 'Stack',
    summary: 'Reverse rotate top three items',
    description: 'Rotates the top item to the third position, shifting the other two up.',
    example: '1 2 3 -ROT . . .  \\ prints 2 1 3',
    opcode: Opcode.MROT,
  },
  {
    name: '2DUP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x1 x2 x1 x2 )',
    category: 'Stack',
    summary: 'Duplicate top pair of items',
    description: 'Duplicates the top two items on the stack in order.',
    example: '10 20 2DUP . . . .  \\ prints 20 10 20 10',
    opcode: Opcode.TWODUP,
  },
  {
    name: '2DROP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- )',
    category: 'Stack',
    summary: 'Discard top pair of items',
    description: 'Removes the top two items from the data stack.',
    example: '1 2 3 2DROP .  \\ prints 1',
    opcode: Opcode.TWODROP,
  },
  {
    name: '2SWAP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 x3 x4 -- x3 x4 x1 x2 )',
    category: 'Stack',
    summary: 'Swap top two pairs of items',
    description: 'Swaps the top two pairs of values on the stack.',
    example: '1 2 3 4 2SWAP . . . .  \\ prints 2 1 4 3',
    opcode: Opcode.TWOSWAP,
  },
  {
    name: 'NIP',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x2 )',
    category: 'Stack',
    summary: 'Drop second item on stack',
    description: 'Discards the item just below the top of the stack.',
    example: '10 20 NIP .  \\ prints 20',
    opcode: Opcode.NIP,
  },
  {
    name: 'TUCK',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x2 x1 x2 )',
    category: 'Stack',
    summary: 'Copy TOS under second item',
    description: 'Inserts a copy of the top item below the second item on the stack.',
    example: '10 20 TUCK . . .  \\ prints 20 10 20',
    opcode: Opcode.TUCK,
  },
  {
    name: 'DEPTH',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- n )',
    category: 'Stack',
    summary: 'Return current stack count',
    description: 'Pushes the number of items currently on the data stack.',
    example: '10 20 30 DEPTH .  \\ prints 3',
    opcode: Opcode.DEPTH,
  },
  {
    name: 'CLEAR',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( ... -- )',
    category: 'Stack',
    summary: 'Clear entire data stack',
    description: 'Discards all values currently on the data stack.',
    example: '1 2 3 4 CLEAR DEPTH .  \\ prints 0',
    opcode: Opcode.CLEAR,
  },

  // --- Arithmetic & Math ---
  {
    name: '+',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- n3 )',
    category: 'Arithmetic',
    summary: 'Addition',
    description: 'Adds n1 and n2, pushing the sum n3.',
    example: '15 25 + .  \\ prints 40',
    opcode: Opcode.ADD,
  },
  {
    name: '-',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- n3 )',
    category: 'Arithmetic',
    summary: 'Subtraction',
    description: 'Subtracts n2 from n1, pushing the difference n3.',
    example: '50 18 - .  \\ prints 32',
    opcode: Opcode.SUB,
  },
  {
    name: '*',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- n3 )',
    category: 'Arithmetic',
    summary: 'Multiplication',
    description: 'Multiplies n1 by n2, pushing the product n3.',
    example: '6 7 * .  \\ prints 42',
    opcode: Opcode.MUL,
  },
  {
    name: '/',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- n3 )',
    category: 'Arithmetic',
    summary: 'Integer division',
    description: 'Divides n1 by n2, pushing the integer quotient n3.',
    example: '100 8 / .  \\ prints 12',
    opcode: Opcode.DIV,
  },
  {
    name: 'MOD',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- rem )',
    category: 'Arithmetic',
    summary: 'Remainder modulo',
    description: 'Computes the remainder of dividing n1 by n2.',
    example: '100 8 MOD .  \\ prints 4',
    opcode: Opcode.MOD,
  },
  {
    name: '/MOD',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- rem quot )',
    category: 'Arithmetic',
    summary: 'Division and remainder',
    description: 'Computes both division and remainder. Pushes remainder, then quotient.',
    example: '100 8 /MOD . .  \\ prints 12 4',
    opcode: Opcode.DIVMOD,
  },
  {
    name: 'NEGATE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- -n )',
    category: 'Arithmetic',
    summary: 'Negate integer',
    description: 'Changes the sign of the top stack item.',
    example: '42 NEGATE .  \\ prints -42',
    opcode: Opcode.NEG,
  },
  {
    name: 'ABS',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- |n| )',
    category: 'Arithmetic',
    summary: 'Absolute value',
    description: 'Replaces the top stack item with its absolute value.',
    example: '-50 ABS .  \\ prints 50',
    opcode: Opcode.ABS,
  },
  {
    name: 'MIN',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- min )',
    category: 'Arithmetic',
    summary: 'Minimum of two numbers',
    description: 'Pushes the lesser of n1 and n2.',
    example: '15 42 MIN .  \\ prints 15',
    opcode: Opcode.MIN,
  },
  {
    name: 'MAX',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- max )',
    category: 'Arithmetic',
    summary: 'Maximum of two numbers',
    description: 'Pushes the greater of n1 and n2.',
    example: '15 42 MAX .  \\ prints 42',
    opcode: Opcode.MAX,
  },
  {
    name: '1+',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- n+1 )',
    category: 'Arithmetic',
    summary: 'Increment by 1',
    description: 'Adds 1 to the top stack item efficiently.',
    example: '9 1+ .  \\ prints 10',
    opcode: Opcode.INC,
  },
  {
    name: '1-',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- n-1 )',
    category: 'Arithmetic',
    summary: 'Decrement by 1',
    description: 'Subtracts 1 from the top stack item efficiently.',
    example: '10 1- .  \\ prints 9',
    opcode: Opcode.DEC,
  },
  {
    name: '2*',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- n*2 )',
    category: 'Arithmetic',
    summary: 'Multiply by 2',
    description: 'Performs a bitwise arithmetic left shift (n << 1).',
    example: '7 2* .  \\ prints 14',
    opcode: Opcode.TWOMUL,
  },
  {
    name: '2/',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- n/2 )',
    category: 'Arithmetic',
    summary: 'Divide by 2',
    description: 'Performs a bitwise arithmetic right shift (n >> 1).',
    example: '14 2/ .  \\ prints 7',
    opcode: Opcode.TWODIV,
  },
  {
    name: 'SQRT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- sqrt )',
    category: 'Arithmetic',
    summary: 'Integer square root',
    description: 'Computes the floor integer square root of n.',
    example: '144 SQRT .  \\ prints 12',
    opcode: Opcode.SQRT,
  },

  // --- Comparison & Logic ---
  {
    name: '=',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- flag )',
    category: 'Logic',
    summary: 'Equal comparison',
    description: 'Pushes -1 (true) if x1 equals x2; otherwise pushes 0 (false).',
    example: '10 10 = .  \\ prints -1',
    opcode: Opcode.EQ,
  },
  {
    name: '<>',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- flag )',
    category: 'Logic',
    summary: 'Not equal comparison',
    description: 'Pushes -1 (true) if x1 is not equal to x2; otherwise 0.',
    example: '5 8 <> .  \\ prints -1',
    opcode: Opcode.NEQ,
  },
  {
    name: '<',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- flag )',
    category: 'Logic',
    summary: 'Less than comparison',
    description: 'Pushes -1 (true) if n1 < n2; otherwise 0.',
    example: '3 5 < .  \\ prints -1',
    opcode: Opcode.LT,
  },
  {
    name: '>',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- flag )',
    category: 'Logic',
    summary: 'Greater than comparison',
    description: 'Pushes -1 (true) if n1 > n2; otherwise 0.',
    example: '9 4 > .  \\ prints -1',
    opcode: Opcode.GT,
  },
  {
    name: '<=',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- flag )',
    category: 'Logic',
    summary: 'Less than or equal',
    description: 'Pushes -1 (true) if n1 <= n2; otherwise 0.',
    example: '5 5 <= .  \\ prints -1',
    opcode: Opcode.LTE,
  },
  {
    name: '>=',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n1 n2 -- flag )',
    category: 'Logic',
    summary: 'Greater than or equal',
    description: 'Pushes -1 (true) if n1 >= n2; otherwise 0.',
    example: '7 6 >= .  \\ prints -1',
    opcode: Opcode.GTE,
  },
  {
    name: '0=',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- flag )',
    category: 'Logic',
    summary: 'Equal to zero (logical NOT)',
    description: 'Pushes -1 if x is 0; otherwise pushes 0.',
    example: '0 0= .  \\ prints -1\n5 0= .  \\ prints 0',
    opcode: Opcode.ZEQ,
  },
  {
    name: '0<',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- flag )',
    category: 'Logic',
    summary: 'Less than zero',
    description: 'Pushes -1 if n < 0; otherwise pushes 0.',
    example: '-4 0< .  \\ prints -1',
    opcode: Opcode.ZLT,
  },
  {
    name: '0>',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- flag )',
    category: 'Logic',
    summary: 'Greater than zero',
    description: 'Pushes -1 if n > 0; otherwise pushes 0.',
    example: '8 0> .  \\ prints -1',
    opcode: Opcode.ZGT,
  },
  {
    name: 'AND',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x3 )',
    category: 'Logic',
    summary: 'Bitwise AND',
    description: 'Performs bitwise AND between x1 and x2.',
    example: '12 10 AND .  \\ prints 8',
    opcode: Opcode.AND,
  },
  {
    name: 'OR',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x3 )',
    category: 'Logic',
    summary: 'Bitwise OR',
    description: 'Performs bitwise OR between x1 and x2.',
    example: '12 10 OR .  \\ prints 14',
    opcode: Opcode.OR,
  },
  {
    name: 'XOR',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x1 x2 -- x3 )',
    category: 'Logic',
    summary: 'Bitwise XOR',
    description: 'Performs bitwise XOR between x1 and x2.',
    example: '12 10 XOR .  \\ prints 6',
    opcode: Opcode.XOR,
  },
  {
    name: 'INVERT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- ~x )',
    category: 'Logic',
    summary: 'Bitwise NOT',
    description: 'Flips all bits of the top stack item (~x).',
    example: '0 INVERT .  \\ prints -1',
    opcode: Opcode.INVERT,
  },
  {
    name: 'TRUE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- -1 )',
    category: 'Logic',
    summary: 'Push boolean true',
    description: 'Pushes -1, representing truth in standard Forth.',
    example: 'TRUE .  \\ prints -1',
    opcode: Opcode.TRUE,
  },
  {
    name: 'FALSE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- 0 )',
    category: 'Logic',
    summary: 'Push boolean false',
    description: 'Pushes 0, representing false in standard Forth.',
    example: 'FALSE .  \\ prints 0',
    opcode: Opcode.FALSE,
  },

  // --- Control Structures ---
  {
    name: 'IF ... THEN',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( flag -- )',
    category: 'Control',
    summary: 'Conditional execution',
    description: 'If flag is non-zero, executes the code between IF and THEN. Otherwise jumps past THEN.',
    example: ': CHECK 0= IF ." Zero!" THEN ;',
  },
  {
    name: 'IF ... ELSE ... THEN',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( flag -- )',
    category: 'Control',
    summary: 'Conditional branch with alternate',
    description: 'If flag is non-zero, executes code up to ELSE; otherwise executes code between ELSE and THEN.',
    example: ': POS? 0> IF ." Positive" ELSE ." Not positive" THEN ;',
  },
  {
    name: 'DO ... LOOP',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( limit start -- )',
    category: 'Control',
    summary: 'Counted loop',
    description: 'Sets up a loop counting from start up to limit. Loop body can access index with word I.',
    example: ': COUNTDOWN 10 0 DO I . LOOP ;',
  },
  {
    name: 'I',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- index )',
    category: 'Control',
    summary: 'Current loop index',
    description: 'Pushes the index of the innermost DO...LOOP.',
    example: '5 0 DO I . LOOP  \\ prints 0 1 2 3 4',
    opcode: Opcode.I_INDEX,
  },
  {
    name: 'J',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- outer_index )',
    category: 'Control',
    summary: 'Outer loop index',
    description: 'Pushes the index of the enclosing outer DO...LOOP.',
    example: '3 0 DO 3 0 DO J . I . CR LOOP LOOP',
    opcode: Opcode.J_INDEX,
  },
  {
    name: 'BEGIN ... UNTIL',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( -- ) (loop: ... flag -- )',
    category: 'Control',
    summary: 'Repeat loop until flag is true',
    description: 'Repeats the loop body until the condition flag on top of stack is non-zero (true).',
    example: '5 BEGIN DUP . 1- DUP 0= UNTIL DROP',
  },
  {
    name: 'BEGIN ... WHILE ... REPEAT',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( -- ) (loop: ... flag -- )',
    category: 'Control',
    summary: 'Pre-conditioned loop',
    description: 'Evaluates condition at WHILE; if non-zero continues through REPEAT back to BEGIN; otherwise exits.',
    example: ': GCD BEGIN DUP WHILE TUCK MOD REPEAT DROP ;',
  },

  // --- Memory & Variables ---
  {
    name: 'VARIABLE',
    isPrimitive: false,
    isImmediate: false,
    stackEffect: '( "name" -- )',
    category: 'Memory',
    summary: 'Define a 32-bit variable',
    description: 'Allocates a 4-byte memory location and defines a word that pushes its address.',
    example: 'VARIABLE COUNT\n10 COUNT !\nCOUNT ?  \\ prints 10',
  },
  {
    name: 'CONSTANT',
    isPrimitive: false,
    isImmediate: false,
    stackEffect: '( val "name" -- )',
    category: 'Memory',
    summary: 'Define a named constant',
    description: 'Creates a word that pushes the designated value when invoked.',
    example: '100 CONSTANT MAX-VAL\nMAX-VAL .  \\ prints 100',
  },
  {
    name: '@',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( a-addr -- x )',
    category: 'Memory',
    summary: 'Fetch value from address',
    description: 'Reads 32-bit value from memory address a-addr and pushes it onto stack.',
    example: 'COUNT @ .  \\ prints value of COUNT',
    opcode: Opcode.LOAD,
  },
  {
    name: '!',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x a-addr -- )',
    category: 'Memory',
    summary: 'Store value into address',
    description: 'Stores 32-bit value x into memory at address a-addr.',
    example: '42 COUNT !  \\ writes 42 into COUNT',
    opcode: Opcode.STORE,
  },
  {
    name: '+!',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n a-addr -- )',
    category: 'Memory',
    summary: 'Add to memory location',
    description: 'Adds n to the 32-bit value stored at address a-addr.',
    example: '1 COUNT +!  \\ increments COUNT by 1',
    opcode: Opcode.ADD_STORE,
  },
  {
    name: '?',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( a-addr -- )',
    category: 'Memory',
    summary: 'Fetch and display value',
    description: 'Reads the value at address a-addr and displays it followed by a space.',
    example: 'COUNT ?  \\ prints value at COUNT',
    opcode: Opcode.FETCH_PRINT,
  },
  {
    name: 'ALLOT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- )',
    category: 'Memory',
    summary: 'Allocate n bytes in memory',
    description: 'Advances the data space allocation pointer (HERE) by n bytes.',
    example: 'VARIABLE BUFFER 64 ALLOT',
    opcode: Opcode.ALLOT,
  },
  {
    name: 'HERE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- addr )',
    category: 'Memory',
    summary: 'Current data space pointer',
    description: 'Pushes the current address of the data space allocation pointer.',
    example: 'HERE .  \\ prints current memory pointer',
    opcode: Opcode.HERE,
  },
  {
    name: 'C@',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( c-addr -- char )',
    category: 'Memory',
    summary: 'Fetch byte from address',
    description: 'Reads an 8-bit byte from memory address c-addr.',
    example: 'BUFFER C@ .',
    opcode: Opcode.C_LOAD,
  },
  {
    name: 'C!',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( char c-addr -- )',
    category: 'Memory',
    summary: 'Store byte into address',
    description: 'Stores an 8-bit byte into memory address c-addr.',
    example: '65 BUFFER C!  \\ stores ASCII "A"',
    opcode: Opcode.C_STORE,
  },

  // --- Return Stack ---
  {
    name: '>R',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( x -- ) (R: -- x)',
    category: 'Return Stack',
    summary: 'Move TOS to Return Stack',
    description: 'Pops value from data stack and pushes it onto the return stack.',
    example: ': SQ-PLUS >R DUP * R> + ;  \\ ( x y -- x^2 + y )',
    opcode: Opcode.TO_R,
  },
  {
    name: 'R>',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- x ) (R: x -- )',
    category: 'Return Stack',
    summary: 'Move from Return Stack to TOS',
    description: 'Pops value from the return stack and pushes it onto the data stack.',
    example: '10 >R R> .  \\ prints 10',
    opcode: Opcode.FROM_R,
  },
  {
    name: 'R@',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- x ) (R: x -- x)',
    category: 'Return Stack',
    summary: 'Copy top of Return Stack',
    description: 'Copies top item of return stack without popping it.',
    example: '10 >R R@ . R> DROP  \\ prints 10',
    opcode: Opcode.FETCH_R,
  },

  // --- I/O & Output ---
  {
    name: '.',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- )',
    category: 'I/O',
    summary: 'Print number and space',
    description: 'Pops top integer from stack and prints it to the console followed by a space.',
    example: '42 .  \\ prints "42 "',
    opcode: Opcode.DOT,
  },
  {
    name: '.S',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- )',
    category: 'I/O',
    summary: 'Inspect stack non-destructively',
    description: 'Prints current stack contents without removing any items.',
    example: '10 20 30 .S  \\ prints "<3> 10 20 30"',
    opcode: Opcode.DOT_S,
  },
  {
    name: 'CR',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- )',
    category: 'I/O',
    summary: 'Carriage return / Newline',
    description: 'Emits a carriage return and line feed to the console output.',
    example: '." Hello" CR ." World"',
    opcode: Opcode.CR,
  },
  {
    name: 'EMIT',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( char -- )',
    category: 'I/O',
    summary: 'Print character code',
    description: 'Pops character code from stack and outputs corresponding ASCII character.',
    example: '65 EMIT  \\ prints "A"',
    opcode: Opcode.EMIT,
  },
  {
    name: 'SPACE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- )',
    category: 'I/O',
    summary: 'Print single space',
    description: 'Outputs a single ASCII space character (32).',
    example: '42 . SPACE 43 .',
    opcode: Opcode.SPACE,
  },
  {
    name: 'SPACES',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( n -- )',
    category: 'I/O',
    summary: 'Print n spaces',
    description: 'Pops n and outputs n spaces to the console.',
    example: '5 SPACES ." Indented"',
    opcode: Opcode.SPACES,
  },
  {
    name: '."',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( "ccc<quote>" -- )',
    category: 'I/O',
    summary: 'Print inline string literal',
    description: 'Compiles or prints literal string delimited by closing quote character `"`.',
    example: '." Hello Forth World!" CR',
    opcode: Opcode.PRINT_STR,
  },
  {
    name: 'PAGE',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- )',
    category: 'I/O',
    summary: 'Clear console display',
    description: 'Clears the output terminal buffer.',
    example: 'PAGE',
    opcode: Opcode.PAGE,
  },

  // --- Defining Words & System ---
  {
    name: ':',
    isPrimitive: false,
    isImmediate: false,
    stackEffect: '( "name" -- )',
    category: 'Defining',
    summary: 'Begin colon definition',
    description: 'Creates a new dictionary word and enters compilation mode.',
    example: ': SQUARE DUP * ;',
  },
  {
    name: ';',
    isPrimitive: false,
    isImmediate: true,
    stackEffect: '( -- )',
    category: 'Defining',
    summary: 'End colon definition',
    description: 'Compiles return opcode and exits compilation mode back to interpretation.',
    example: ': DOUBLE 2 * ;',
  },
  {
    name: 'SEE',
    isPrimitive: false,
    isImmediate: false,
    stackEffect: '( "name" -- )',
    category: 'System',
    summary: 'Decompile and inspect word',
    description: 'Disassembles and displays the stack bytecode and definition of the specified word.',
    example: 'SEE SQUARE',
  },
  {
    name: 'WORDS',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- )',
    category: 'System',
    summary: 'List dictionary words',
    description: 'Prints names of all defined words currently in the dictionary.',
    example: 'WORDS',
  },
  {
    name: 'TICKS',
    isPrimitive: true,
    isImmediate: false,
    stackEffect: '( -- ms )',
    category: 'System',
    summary: 'System millisecond timestamp',
    description: 'Pushes the current high-resolution system clock in milliseconds.',
    example: 'TICKS .',
    opcode: Opcode.TICKS,
  }
];

export const FORTH_CATEGORIES = [
  'All',
  'Stack',
  'Arithmetic',
  'Logic',
  'Control',
  'Memory',
  'Return Stack',
  'I/O',
  'Defining',
  'System'
];
